jtzs-src/com/xes/jtzs/model/Answer.java
/*
 * Powered By [up72-framework]
 * Web Site: http://www.up72.com
 * Since 2006 - 2013
 */

package com.xes.jtzs.model;

import static com.up72.common.CommonUtils.*;

import java.util.Date;

import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;

import javax.validation.constraints.*;
import org.hibernate.validator.constraints.*;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;
import java.util.*;

import com.up72.base.*;
import com.up72.util.*;

import com.up72.framework.util.*;
import com.up72.framework.util.holder.ApplicationContextHolder;
import com.up72.framework.web.util.*;
import com.up72.framework.page.*;
import com.up72.framework.page.impl.*;

import com.xes.jtzs.model.*;
import com.xes.jtzs.dao.*;
import com.xes.jtzs.service.*;
import com.xes.jtzs.vo.query.*;/**
 * 
 * 
 * @author 
 * @version 1.0
 * @since 1.0
 */
@Entity
@Table(name = "xes_jtzs_answer")
public class Answer extends BaseEntity implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	//alias
	public static final String TABLE_ALIAS = "答案";
	public static final String ALIAS_ID = "id";
	public static final String ALIAS_QUESTION_ID = "问题";
	public static final String ALIAS_TEACHER_ID = "回答老师";
	public static final String ALIAS_CONTENT = "答案";
	public static final String ALIAS_IMG_PATH = "答案图片";
	public static final String ALIAS_IDER = "解题思路";
	public static final String ALIAS_ANSWER_TIME = "作答时间";
	public static final String ALIAS_STATUS = "答题状态";
	
	//date formats
	public static final String FORMAT_ANSWER_TIME = DATE_FORMAT;
	

	//可以直接使用: @Length(max=50,message="用户名长度不能大于50")显示错误消息
	//columns START
	/** */
	
	private java.lang.Long id;
	
	/** 问题ID*/
	
	private java.lang.Long questionId;
	
	/** 老师ID*/
	
	private java.lang.Long teacherId;
	
	/** 问题内容*/
	@Length(max=500)
	private java.lang.String content;
	
	/** 问题图片*/
	@Length(max=200)
	private java.lang.String imgPath;
	
	/** 解题思路*/
	@Length(max=500)
	private java.lang.String ider;
	
	/** 作答时间*/
	
	private java.lang.Long answerTime;
	
	/** 答题状态*/
	@Max(127)
	private Integer status;
	
	//columns END


	public Answer(){
	}

	public Answer(
		java.lang.Long id
	){
		this.id = id;
	}

	

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Column(name = "ID", unique = true, nullable = false, insertable = true, updatable = true, length = 19)
	public java.lang.Long getId() {
		return this.id;
	}
	
	@Column(name = "QUESTION_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getQuestionId() {
		return this.questionId;
	}
	
	public void setQuestionId(java.lang.Long value) {
		this.questionId = value;
	}
	
	@Column(name = "TEACHER_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getTeacherId() {
		return this.teacherId;
	}
	
	public void setTeacherId(java.lang.Long value) {
		this.teacherId = value;
	}
	
	@Column(name = "CONTENT", unique = false, nullable = true, insertable = true, updatable = true, length = 500)
	public java.lang.String getContent() {
		return this.content==null?this.content:this.content.replace("\r", "\\r").replace("\n", "\\n");
	}
	
	public void setContent(java.lang.String value) {
		this.content = value;
	}
	
	@Column(name = "IMG_PATH", unique = false, nullable = true, insertable = true, updatable = true, length = 200)
	public java.lang.String getImgPath() {
		return this.imgPath;
	}
	
	public void setImgPath(java.lang.String value) {
		this.imgPath = value;
	}
	
	@Column(name = "IDER", unique = false, nullable = true, insertable = true, updatable = true, length = 500)
	public java.lang.String getIder() {
		return this.ider==null?this.ider:this.ider.replace("\r", "\\r").replace("\n", "\\n");
	}
	
	public void setIder(java.lang.String value) {
		this.ider = value;
	}
	
	@Transient
	public Date getAnswerTimeDate() {
		return dateUtils.longToDate(this.answerTime);
	}
	@Column(name = "ANSWER_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getAnswerTime() {
		return this.answerTime;
	}
	
	public void setAnswerTime(java.lang.Long value) {
		this.answerTime = value;
	}
	
	@Column(name = "STATUS", unique = false, nullable = true, insertable = true, updatable = true, length = 3)
	public Integer getStatus() {
		return this.status;
	}
	
	public void setStatus(Integer value) {
		this.status = value;
	}
	

	public String toString() {
		return new ToStringBuilder(this,ToStringStyle.MULTI_LINE_STYLE)
			.append("Id",getId())
			.append("QuestionId",getQuestionId())
			.append("TeacherId",getTeacherId())
			.append("Content",getContent())
			.append("ImgPath",getImgPath())
			.append("Ider",getIder())
			.append("AnswerTime",getAnswerTime())
			.append("Status",getStatus())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof Answer == false) return false;
		if(this == obj) return true;
		Answer other = (Answer)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
	
	@Transient
	public String getAnswerTimeStr(){
		String rusult = null;
		if(null!= this.answerTime){
			rusult = dateUtils.getRelativeTime(answerTime);
		}
		if(null == rusult){
			rusult = "";
		}
		return rusult;
	}
	
	@Transient
	public Teacher getTeacher(){
		Teacher teacher = null;
		if(null != this.teacherId){
			TeacherManager teacherManager = (TeacherManager)ApplicationContextHolder.getBean("teacherManager");
			teacher = teacherManager.getById(teacherId);
		}
		if(null == teacher){
			teacher = new Teacher();
		}
		return teacher;
	}
	
	@Transient
	public Question getQuestion(){
		Question question = null;
		if(null != this.teacherId){
			QuestionManager questionManager = (QuestionManager)ApplicationContextHolder.getBean("questionManager");
			question = questionManager.getById(this.questionId);
		}
		if(null == question){
			question = new Question();
		}
		return question;
	}
}

jtzs-src/com/xes/jtzs/model/AnswerShow.java
/*
 * Powered By [up72-framework]
 * Web Site: http://www.up72.com
 * Since 2006 - 2014
 */

package com.xes.jtzs.model;

import static com.up72.common.CommonUtils.*;
import java.util.Date;

import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;

import javax.validation.constraints.*;
import org.hibernate.validator.constraints.*;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;
import java.util.*;

import com.up72.base.*;
import com.up72.util.*;

import com.up72.framework.util.*;
import com.up72.framework.web.util.*;
import com.up72.framework.page.*;
import com.up72.framework.page.impl.*;

import com.xes.jtzs.model.*;
import com.xes.jtzs.dao.*;
import com.xes.jtzs.service.*;
import com.xes.jtzs.vo.query.*;/**
 * 
 * 
 * @author 
 * @version 1.0
 * @since 1.0
 */
@Entity
@Table(name = "xes_jtzs_answer_show")
public class AnswerShow extends BaseEntity implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	//alias
	public static final String TABLE_ALIAS = "AnswerShow";
	public static final String ALIAS_ID = "id";
	public static final String ALIAS_QUESTION_ID = "问题ID";
	public static final String ALIAS_ANSWER_ID = "答案ID";
	public static final String ALIAS_STUDENT_ID = "学生ID";
	public static final String ALIAS_ADD_TIME = "添加时间";
	
	//date formats
	public static final String FORMAT_ADD_TIME = DATE_FORMAT;
	

	//可以直接使用: @Length(max=50,message="用户名长度不能大于50")显示错误消息
	//columns START
	/** */
	
	private java.lang.Long id;
	
	/** 问题ID*/
	
	private java.lang.Long questionId;
	
	/** 答案ID*/
	
	private java.lang.Long answerId;
	
	/** 学生ID*/
	
	private java.lang.Long studentId;
	
	/** 添加时间*/
	
	private java.lang.Long addTime;
	
	//columns END


	public AnswerShow(){
	}

	public AnswerShow(
		java.lang.Long id
	){
		this.id = id;
	}

	

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Column(name = "ID", unique = true, nullable = false, insertable = true, updatable = true, length = 19)
	public java.lang.Long getId() {
		return this.id;
	}
	
	@Column(name = "QUESTION_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getQuestionId() {
		return this.questionId;
	}
	
	public void setQuestionId(java.lang.Long value) {
		this.questionId = value;
	}
	
	@Column(name = "ANSWER_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getAnswerId() {
		return this.answerId;
	}
	
	public void setAnswerId(java.lang.Long value) {
		this.answerId = value;
	}
	
	@Column(name = "STUDENT_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getStudentId() {
		return this.studentId;
	}
	
	public void setStudentId(java.lang.Long value) {
		this.studentId = value;
	}
	
	@Transient
	public Date getAddTimeDate() {
		return dateUtils.longToDate(this.addTime);
	}
	@Column(name = "ADD_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getAddTime() {
		return this.addTime;
	}
	
	public void setAddTime(java.lang.Long value) {
		this.addTime = value;
	}
	

	public String toString() {
		return new ToStringBuilder(this,ToStringStyle.MULTI_LINE_STYLE)
			.append("Id",getId())
			.append("QuestionId",getQuestionId())
			.append("AnswerId",getAnswerId())
			.append("StudentId",getStudentId())
			.append("AddTime",getAddTime())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof AnswerShow == false) return false;
		if(this == obj) return true;
		AnswerShow other = (AnswerShow)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

jtzs-src/com/xes/jtzs/model/Area.java
/*
 * Powered By [up72-framework]
 * Web Site: http://www.up72.com
 * Since 2006 - 2013
 */

package com.xes.jtzs.model;

import javax.persistence.*;

import javax.validation.constraints.*;
import org.hibernate.validator.constraints.*;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.up72.base.*;
import com.up72.framework.util.holder.ApplicationContextHolder;
import com.xes.jtzs.JTZSConstants;
import com.xes.jtzs.service.CityManager;
import com.xes.jtzs.service.ProvinceManager;
/**
 * 
 * 
 * @author 
 * @version 1.0
 * @since 1.0
 */
@Entity
@Table(name = "xes_jtzs_area")
public class Area extends BaseEntity implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	//alias
	public static final String TABLE_ALIAS = "区县";
	public static final String ALIAS_ID = "id";
	public static final String ALIAS_NAME = "区县名称";
	public static final String ALIAS_SORT = "排序";
	public static final String ALIAS_EN_NAME = "区县拼音";
	public static final String ALIAS_STATUS = "状态";//(1为启用，0为不禁用)默认1
	public static final String ALIAS_CITY_ID = "城市";
	public static final String ALIAS_PROVINCE_ID = "省份";
	
	//date formats
	

	//可以直接使用: @Length(max=50,message="用户名长度不能大于50")显示错误消息
	//columns START
	/** */
	
	private java.lang.Long id;
	
	/** 区县名称*/
	@Length(max=50)
	private java.lang.String name;
	
	/** 排序*/
	
	private java.lang.Long sort;
	
	/** 区县拼音*/
	@Length(max=200)
	private java.lang.String enName;
	
	/** 是否显示(1为显示，0为不显示)*/
	@Max(127)
	private Integer status;
	
	/** 城市ID*/
	private java.lang.Long cityId;
	/** 省份ID*/
	
	private java.lang.Long provinceId;
	
	//columns END


	public Area(){
	}

	public Area(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Column(name = "ID", unique = true, nullable = false, insertable = true, updatable = true, length = 19)
	public java.lang.Long getId() {
		return this.id;
	}
	
	@Column(name = "NAME", unique = false, nullable = true, insertable = true, updatable = true, length = 50)
	public java.lang.String getName() {
		return this.name;
	}
	
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	@Column(name = "SORT", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getSort() {
		return this.sort;
	}
	
	public void setSort(java.lang.Long value) {
		this.sort = value;
	}
	
	@Column(name = "EN_NAME", unique = false, nullable = true, insertable = true, updatable = true, length = 200)
	public java.lang.String getEnName() {
		return this.enName;
	}
	
	public void setEnName(java.lang.String value) {
		this.enName = value;
	}
	
	@Column(name = "STATUS", unique = false, nullable = true, insertable = true, updatable = true, length = 3)
	public Integer getStatus() {
		return this.status;
	}
	
	public void setStatus(Integer value) {
		this.status = value;
	}
	
	@Column(name = "CITY_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getCityId() {
		return this.cityId;
	}
	
	public void setCityId(java.lang.Long value) {
		this.cityId = value;
	}
	@Column(name = "PROVINCE_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getProvinceId() {
		return this.provinceId;
	}
	
	public void setProvinceId(java.lang.Long value) {
		this.provinceId = value;
	}

	public String toString() {
		return new ToStringBuilder(this,ToStringStyle.MULTI_LINE_STYLE)
			.append("Id",getId())
			.append("Name",getName())
			.append("Sort",getSort())
			.append("EnName",getEnName())
			.append("Status",getStatus())
			.append("CityId",getCityId())
			.append("ProvinceId",getProvinceId())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof Area == false) return false;
		if(this == obj) return true;
		Area other = (Area)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
	
	@Transient
	public City getCity(){
		CityManager cityManager = (CityManager)ApplicationContextHolder.getBean("cityManager");
		City city = null;
		if(null != this.getCityId()){
			city = cityManager.getById(this.getCityId());
		}
		if(null == city){
			city = new City();
		}
		return city;
	}
	
	@Transient
	public Province getProvince(){
		ProvinceManager provinceManager = (ProvinceManager)ApplicationContextHolder.getBean("provinceManager");
		Province province = null;
		if(null != this.getProvinceId()){
			province = provinceManager.getById(this.getProvinceId());
		}
		if(null == province){
			province = new Province();
		}
		return province;
	}
	
	@Transient
	public String getStatusStr(){
		String result = JTZSConstants.Pubilc.DISABLE.getName();
		if(null != this.status && JTZSConstants.Pubilc.ENABLED.getIndex()==this.status){
			result = JTZSConstants.Pubilc.ENABLED.getName();
		}
		return result;
	}
}

WebRoot/pages/admin/jtzs/city/base.jsp
<jsp:include page="/admin/adminBase" />

WebRoot/pages/admin/jtzs/city/batch_edit.jsp
<%@page import="com.xes.jtzs.model.*" %>
<%@ page trimDirectiveWhitespaces="true" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp" %>
<div class="up72_edit">
  <table border="0" cellspacing="0" cellpadding="0" width="100%" class="edit_table">
    <tr class="frmtr">
      <th class="frmth"><label><%=City.ALIAS_NAME%>：</label></th>
      <td class="frmtd">        <input id="name" class=" input_txt" maxlength="50" />
         </td>
    </tr>
    <tr class="frmtr">
      <th class="frmth"><label><%=City.ALIAS_SORT%>：</label></th>
      <td class="frmtd">        <input id="sort" class="digits  input_txt" maxlength="19" />
         </td>
    </tr>
    <tr class="frmtr">
      <th class="frmth"><label><%=City.ALIAS_EN_NAME%>：</label></th>
      <td class="frmtd">        <input id="enName" class=" input_txt" maxlength="200" />
         </td>
    </tr>
    <tr class="frmtr">
      <th class="frmth"><label><%=City.ALIAS_PROVINCE_ID%>：</label></th>
      <td class="frmtd">        <input id="provinceId" class="digits  input_txt" maxlength="19" />
         </td>
    </tr>
    <tr class="frmtr">
      <th class="frmth"><label><%=City.ALIAS_STATUS%>：</label></th>
      <td class="frmtd">        <input id="status" class="digits  input_txt" maxlength="3" />
         </td>
    </tr>
  </table>
</div>

WebRoot/pages/admin/jtzs/city/edit.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp" %>
<%@ page trimDirectiveWhitespaces="true" %>
<div class="up72_edit">
  <form:form id="admin_jtzs_city_edit_form" method="put" action="${ctx}/admin/jtzs/city/${city.id}" modelAttribute="city">
    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="edit_table">
      <%@ include file="form_include.jsp" %>
    </table>
    <div class="up72_submit">
      <div class="btn btn_sub" title="完成"><input type="submit" id="submitButton" name="submitButton" value="完成" /></div>
      <div class="btn btn_cel" title="取消"><input type="button" id="close_button" value="取消" onclick="closeBox();" /></div>
    </div>
  </form:form>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$("#admin_jtzs_city_edit_form").validate({
			/*  
			// ajax提交方式
			submitHandler:function(form){   
				form.submit();
			},
			*/
			rules: {
				name:{
					required:true,
					byteMax:50,
					remote:{
						url:'${ctx}/admin/jtzs/city/isUnique',
						data:{
							id:'${city.id}',
							provinceId:function(){
								return $("#admin_jtzs_city_edit_form #provinceId option:selected").val();
							}
						}
					}
				}
			},
			messages:{
				name:{
					remote:'内容不能重复',
					required:'请填写内容',
					byteMax:'不能大于50字'
				}
			},
			errorPlacement: function(error, element) {
				error.appendTo(element.parent());
			}
		});	
	});
</script>

WebRoot/pages/admin/jtzs/city/index.jsp
<%@page import="com.xes.jtzs.model.*" %>

<%@ page contentType="text/html;charset=UTF-8" %>
<%@page import="com.xes.jtzs.JTZSConstants"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib tagdir="/WEB-INF/tags/simpletable" prefix="simpletable"%>
<%@ include file="/common/taglibs.jsp" %>
<%@ page trimDirectiveWhitespaces="true" %>
<up72:override name="head">
  <title><%=City.TABLE_ALIAS%> 维护</title>
  <script src="${ctx}/scripts/rest.js" ></script>
  <link href="${ctx}/scripts/simpletable/simpletable.css" type="text/css" rel="stylesheet">
  <script type="text/javascript" src="${ctx}/scripts/simpletable/simpletable.js"></script> 
  <script type="text/javascript" src="${ctx}/scripts/columnshow.js"></script>
  <link href="${ctx}/scripts/grid/css/flexigrid.css" type="text/css" rel="stylesheet">
  <script type="text/javascript" src="${ctx}/scripts/grid/flexigrid-source.js"></script> 
  <script type="text/javascript" >
		$(document).ready(function() {
			// 分页需要依赖的初始化动作
			window.simpleTable = new SimpleTable('admin_jtzs_city_search_form',${page.thisPageNumber},${page.pageSize},'${pageRequest.sortColumns}');
		});
	</script> 
  <script type="text/javascript" src="<c:url value="/scripts/extend.div.1.0.js"/>"></script> 
</up72:override>
<up72:override name="content"> 
  
  <!--搜索-->
  <div class="up72_search">
    <form id="admin_jtzs_city_search_form" name="admin_jtzs_city_search_form" method="get">
      <div class="search_con"> 
        <div class="search_txt"><%=City.ALIAS_PROVINCE_ID%>：
       		<select id="provinceId" name="provinceId">
			 	<option value="0" <c:if test="${item.id == query.provinceId}">selected="selected"</c:if> >全部</option>
	       		<c:forEach items="${provinceList}" var="item" varStatus="status">
				 	<option value="${item.id}" <c:if test="${item.id == query.provinceId}">selected="selected"</c:if> >${item.name}</option>
	       		</c:forEach>
			</select>
        </div>
        <div class="search_txt"><%=City.ALIAS_NAME%>：
          <input type="text" id="name" name="name" class="input_text" value="${query.name}">
        </div>
        <div class="search_btn">
          <div class="input_button">
            <button name="btnU" type="submit" onclick="$(this).parents('form').submit();" class="button" value="查询"><span>查询</span></button>
          </div>
        </div>
      </div>
    </form>
  </div>
  <!--end搜索-->
  
  <form id="admin_jtzs_city_page_form" name="admin_jtzs_city_page_form" method="get">
    <table id="admin_jtzs_city_table">
      <thead>
        <tr>
          <th showColumn="index" width="50">序号</th>
          <th showColumn="provinceId" width="200"><%=City.ALIAS_PROVINCE_ID%></th>
          <th showColumn="name" width="200"><%=City.ALIAS_NAME%></th>
          <th showColumn="status" width="100">状态</th>
          <th showColumn="option" width="100"><label>操作</label></th>
        </tr>
      </thead>
      <tbody>
        <c:forEach items="${page.result}" var="item" varStatus="status">
          <tr>
            <td showColumn="index">${page.thisPageFirstElementNumber + status.index}</td>
            <td showColumn="provinceId"><c:out value='${item.province.name}'/></td>
            <td showColumn="name"><c:out value='${item.name}'/></td>
            <td showColumn="status"><c:out value='${item.statusStr}'/></td>
            <td showColumn="option">
            	<a href="javascript:;"  onclick="show('${ctx}/admin/jtzs/city/${item.id}/edit','<%=City.TABLE_ALIAS%>',600)" class="sysiconBtnNoIcon">编辑</a>
            	<c:forEach items="${statusArray}" var="item2">
            		<c:if test="${item2.index != item.status}">
		            	<a href="javascript:;" onclick="doValid(${item.id},this)" id="status" class="sysiconBtnNoIcon">${item2.name}</a>
            		</c:if>
            	</c:forEach>
            </td>
          </tr>
        </c:forEach>
      </tbody>
    </table>
    <simpletable:pageToolbar page="${page}"></simpletable:pageToolbar>
  </form>
  <script type="text/javascript">
	// 列选择显示处理
	$.showcolumn(${showColumn});
	
	// 表格列表处理
	$('#admin_jtzs_city_table').flexigrid({
		height: 'auto',
		striped : true,
		buttons : [
			{name: "添加", bclass: "addorder", onpress : function(){show("${ctx}/admin/jtzs/city/new","<%=City.TABLE_ALIAS%>添加",600)}}
		]
	});
	
	function doValid(id,item){
		var $item = $(item);
		$.ajax({
			url : "${ctx}/admin/jtzs/city/"+id+"/doValid",
			type : "post",
			dataType : "json",
			success : function(jsondatas){
				if(jsondatas.status=='success'){
					if(jsondatas.valid=='<%=JTZSConstants.Pubilc.DISABLE.getIndex()%>'){
						$item.text('<%=JTZSConstants.Pubilc.ENABLED.getName()%>');
						$item.closest("tr").find("td[showColumn='status'] div").text('<%=JTZSConstants.Pubilc.DISABLE.getName()%>');
					}else{
						$item.text('<%=JTZSConstants.Pubilc.DISABLE.getName()%>');
						$item.closest("tr").find("td[showColumn='status'] div").text('<%=JTZSConstants.Pubilc.ENABLED.getName()%>');
					}
				}
			},
			error : function(){
			}
		});
	}
</script> 
</up72:override>
<%@ include file="base.jsp" %>

WebRoot/pages/admin/jtzs/city/show.jsp
<%@page import="com.xes.jtzs.model.*" %>

<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp" %>
<%@ page trimDirectiveWhitespaces="true" %>
<div class="up72_show">
  <table cellspacing="0" cellpadding="0" border="0" width="100%" class="show_table">
    <tr class="frmtr"> 
      <th class="frmth"><%=City.ALIAS_NAME%>：</th>
      <td class="frmtd"><c:out value='${city.name}'/></td>
      
      <th class="frmth"><%=City.ALIAS_SORT%>：</th>
      <td class="frmtd"><c:out value='${city.sort}'/></td>
      </tr>
    <tr class="frmtr"> 
      <th class="frmth"><%=City.ALIAS_EN_NAME%>：</th>
      <td class="frmtd"><c:out value='${city.enName}'/></td>
      
      <th class="frmth"><%=City.ALIAS_PROVINCE_ID%>：</th>
      <td class="frmtd"><c:out value='${city.provinceId}'/></td>
      </tr>
    <tr class="frmtr"> 
      <th class="frmth"><%=City.ALIAS_STATUS%>：</th>
      <td class="frmtd"><c:out value='${city.status}'/></td>
      </tr>
  </table>
</div>