jtzs-src/com/xes/jtzs/model/AnswerShow.java
/*
 * Powered By [up72-framework]
 * Web Site: http://www.up72.com
 * Since 2006 - 2014
 */

package com.xes.jtzs.model;

import static com.up72.common.CommonUtils.*;
import java.util.Date;

import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;

import javax.validation.constraints.*;
import org.hibernate.validator.constraints.*;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;
import java.util.*;

import com.up72.base.*;
import com.up72.util.*;

import com.up72.framework.util.*;
import com.up72.framework.web.util.*;
import com.up72.framework.page.*;
import com.up72.framework.page.impl.*;

import com.xes.jtzs.model.*;
import com.xes.jtzs.dao.*;
import com.xes.jtzs.service.*;
import com.xes.jtzs.vo.query.*;/**
 * 
 * 
 * @author 
 * @version 1.0
 * @since 1.0
 */
@Entity
@Table(name = "xes_jtzs_answer_show")
public class AnswerShow extends BaseEntity implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	//alias
	public static final String TABLE_ALIAS = "AnswerShow";
	public static final String ALIAS_ID = "id";
	public static final String ALIAS_QUESTION_ID = "问题ID";
	public static final String ALIAS_ANSWER_ID = "答案ID";
	public static final String ALIAS_STUDENT_ID = "学生ID";
	public static final String ALIAS_ADD_TIME = "添加时间";
	
	//date formats
	public static final String FORMAT_ADD_TIME = DATE_FORMAT;
	

	//可以直接使用: @Length(max=50,message="用户名长度不能大于50")显示错误消息
	//columns START
	/** */
	
	private java.lang.Long id;
	
	/** 问题ID*/
	
	private java.lang.Long questionId;
	
	/** 答案ID*/
	
	private java.lang.Long answerId;
	
	/** 学生ID*/
	
	private java.lang.Long studentId;
	
	/** 添加时间*/
	
	private java.lang.Long addTime;
	
	//columns END


	public AnswerShow(){
	}

	public AnswerShow(
		java.lang.Long id
	){
		this.id = id;
	}

	

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Column(name = "ID", unique = true, nullable = false, insertable = true, updatable = true, length = 19)
	public java.lang.Long getId() {
		return this.id;
	}
	
	@Column(name = "QUESTION_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getQuestionId() {
		return this.questionId;
	}
	
	public void setQuestionId(java.lang.Long value) {
		this.questionId = value;
	}
	
	@Column(name = "ANSWER_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getAnswerId() {
		return this.answerId;
	}
	
	public void setAnswerId(java.lang.Long value) {
		this.answerId = value;
	}
	
	@Column(name = "STUDENT_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getStudentId() {
		return this.studentId;
	}
	
	public void setStudentId(java.lang.Long value) {
		this.studentId = value;
	}
	
	@Transient
	public Date getAddTimeDate() {
		return dateUtils.longToDate(this.addTime);
	}
	@Column(name = "ADD_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getAddTime() {
		return this.addTime;
	}
	
	public void setAddTime(java.lang.Long value) {
		this.addTime = value;
	}
	

	public String toString() {
		return new ToStringBuilder(this,ToStringStyle.MULTI_LINE_STYLE)
			.append("Id",getId())
			.append("QuestionId",getQuestionId())
			.append("AnswerId",getAnswerId())
			.append("StudentId",getStudentId())
			.append("AddTime",getAddTime())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof AnswerShow == false) return false;
		if(this == obj) return true;
		AnswerShow other = (AnswerShow)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

jtzs-src/com/xes/jtzs/model/CommonRule.java
/*
 * Powered By [up72-framework]
 * Web Site: http://www.up72.com
 * Since 2006 - 2013
 */

package com.xes.jtzs.model;

import static com.up72.common.CommonUtils.*;
import java.util.Date;

import javax.persistence.*;

import javax.validation.constraints.*;
import org.hibernate.validator.constraints.*;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.up72.auth.member.model.AuthUser;
import com.up72.auth.member.service.AuthUserManager;
import com.up72.base.*;
import com.up72.framework.util.holder.ApplicationContextHolder;
import com.xes.jtzs.JTZSConstants;

/**
 * 
 * 
 * @author 
 * @version 1.0
 * @since 1.0
 */
@Entity
@Table(name = "xes_jtzs_common_rule")
public class CommonRule extends BaseEntity implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	//alias
	public static final String TABLE_ALIAS = "全局设置";
	public static final String ALIAS_ID = "id";
	public static final String ALIAS_TITLE = "内容";
	public static final String ALIAS_NUM = "数量";
	public static final String ALIAS_SCORE = "积分";
	public static final String ALIAS_SCORE_TYPE = "积分种类";
	public static final String ALIAS_IS_STOP_LOGIN = "是否冻结帐号";//，0为不冻结，1为冻结
	public static final String ALIAS_VALID_START_TIME = "有效开始时间";
	public static final String ALIAS_VALID_STOP_TIME = "有效结束时间";
	public static final String ALIAS_BEGIN_TIME = "开始时间";
	public static final String ALIAS_END_TIME = "结束时间";
	public static final String ALIAS_RULE_TYPE = "规则类型";
	public static final String ALIAS_ADD_TIME = "添加时间";
	public static final String ALIAS_EDIT_TIME = "编辑时间";
	public static final String ALIAS_MINUTE = "分钟";
	public static final String ALIAS_EDIT_USER_ID = "操作人";
	public static final String ALIAS_STATUS = "状态";
	public static final String ALIAS_IS_DEFAULT = "是否默认";
	
	//date formats
	public static final String FORMAT_ADD_TIME = DATE_FORMAT;
	public static final String FORMAT_VALID_START_TIME = DATE_FORMAT;
	public static final String FORMAT_VALID_STOP_TIME = DATE_FORMAT;
	public static final String FORMAT_BEGIN_TIME = DATE_FORMAT;
	public static final String FORMAT_END_TIME = DATE_FORMAT;
	

	//可以直接使用: @Length(max=50,message="用户名长度不能大于50")显示错误消息
	//columns START
	/** */
	
	private java.lang.Long id;
	
	/** 标题*/
	@Length(max=50)
	private java.lang.String title;
	
	/** 数量*/
	@Max(32767)
	private Integer num;
	
	/** 扣除积分*/
	
	private java.lang.Integer score;
	/** 分钟*/
	private java.lang.Integer minute;
	
	/** 是否冻结帐号，0为不冻结，1为冻结*/
	@Max(127)
	private Integer isStopLogin;
	/** 有效开始时间*/
	
	private java.lang.Long validStartTime;
	
	/** 有效结束时间*/
	
	private java.lang.Long validStopTime;
	
	/** 开始时间*/
	
	private java.lang.Long beginTime;
	
	/** 结束时间*/
	
	private java.lang.Long endTime;
	
	/** 规则类型*/
	@Max(127)
	private Integer ruleType;
	
	/** 积分种类*/
	@Max(127)
	private Integer scoreType;
	@Max(127)
	private Integer status;
	@Max(127)
	private Integer isDefault;
	
	/** 添加时间*/
	
	private java.lang.Long addTime;
	/** 编辑时间*/
	
	private java.lang.Long editTime;
	
	/** 操作人 */
	private java.lang.Long editUserId;
	
	//columns END


	public CommonRule(){
	}

	public CommonRule(
		java.lang.Long id
	){
		this.id = id;
	}

	

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Column(name = "ID", unique = true, nullable = false, insertable = true, updatable = true, length = 19)
	public java.lang.Long getId() {
		return this.id;
	}
	
	@Column(name = "TITLE", unique = false, nullable = true, insertable = true, updatable = true, length = 200)
	public String getTitle() {
		return this.title;
	}
	
	public void setTitle(String value) {
		this.title = value;
	}
	
	@Column(name = "NUM", unique = false, nullable = true, insertable = true, updatable = true, length = 5)
	public Integer getNum() {
		return this.num;
	}
	
	public void setNum(Integer value) {
		this.num = value;
	}
	
	@Column(name = "SCORE", unique = false, nullable = true, insertable = true, updatable = true, length = 10)
	public java.lang.Integer getScore() {
		return this.score;
	}
	
	public void setScore(java.lang.Integer value) {
		this.score = value;
	}
	
	@Column(name = "MINUTE", unique = false, nullable = true, insertable = true, updatable = true, length = 10)
	public java.lang.Integer getMinute() {
		return this.minute;
	}
	
	public void setMinute(java.lang.Integer value) {
		this.minute = value;
	}
	
	@Column(name = "IS_STOP_LOGIN", unique = false, nullable = true, insertable = true, updatable = true, length = 3)
	public Integer getIsStopLogin() {
		return this.isStopLogin;
	}
	
	public void setIsStopLogin(Integer value) {
		this.isStopLogin = value;
	}
	
	@Transient
	public Date getValidStartTimeDate() {
		return dateUtils.longToDate(this.validStartTime);
	}
	@Column(name = "VALID_START_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getValidStartTime() {
		return this.validStartTime;
	}
	
	public void setValidStartTime(java.lang.Long value) {
		this.validStartTime = value;
	}
	
	@Transient
	public Date getValidStopTimeDate() {
		return dateUtils.longToDate(this.validStopTime);
	}
	@Column(name = "VALID_STOP_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getValidStopTime() {
		return this.validStopTime;
	}
	
	public void setValidStopTime(java.lang.Long value) {
		this.validStopTime = value;
	}
	
	@Transient
	public Date getBeginTimeDate() {
		return dateUtils.longToDate(this.beginTime);
	}
	
	@Transient
	public String getBeginTimeStr(){
		return null != this.beginTime ? dateUtils.longToTime(this.beginTime).substring(0, 5):"";
	}
	
	@Column(name = "BEGIN_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getBeginTime() {
		return this.beginTime;
	}
	
	public void setBeginTime(java.lang.Long value) {
		this.beginTime = value;
	}
	
	@Transient
	public Date getEndTimeDate() {
		return dateUtils.longToDate(this.endTime);
	}
	
	@Transient
	public String getEndTimeStr() {
		return null != this.endTime ? dateUtils.longToTime(this.endTime).substring(0, 5):"";
	}
	@Column(name = "END_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getEndTime() {
		return this.endTime;
	}
	
	public void setEndTime(java.lang.Long value) {
		this.endTime = value;
	}
	
	@Column(name = "RULE_TYPE", unique = false, nullable = true, insertable = true, updatable = true, length = 3)
	public Integer getRuleType() {
		return this.ruleType;
	}
	
	public void setRuleType(Integer value) {
		this.ruleType = value;
	}
	
	@Column(name = "SCORE_TYPE", unique = false, nullable = true, insertable = true, updatable = true, length = 1)
	public Integer getScoreType() {
		return this.scoreType;
	}
	
	public void setScoreType(Integer value) {
		this.scoreType = value;
	}
	
	@Column(name = "STATUS", unique = false, nullable = true, insertable = true, updatable = true, length = 1)
	public Integer getStatus() {
		return this.status;
	}
	
	public void setStatus(Integer value) {
		this.status = value;
	}
	
	@Column(name = "IS_DEFAULT", unique = false, nullable = true, insertable = true, updatable = true, length = 1)
	public Integer getIsDefault() {
		return this.isDefault;
	}
	
	public void setIsDefault(Integer value) {
		this.isDefault = value;
	}
	
	@Transient
	public Date getAddTimeDate() {
		return dateUtils.longToDate(this.addTime);
	}
	@Column(name = "ADD_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getAddTime() {
		return this.addTime;
	}
	
	public void setAddTime(java.lang.Long value) {
		this.addTime = value;
	}
	
	@Transient
	public Date getEditTimeDate() {
		return dateUtils.longToDate(this.editTime);
	}
	@Column(name = "EDIT_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getEditTime() {
		return this.editTime;
	}
	
	public void setEditTime(java.lang.Long value) {
		this.editTime = value;
	}
	
	@Column(name = "EDIT_USER_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getEditUserId() {
		return this.editUserId;
	}
	
	public void setEditUserId(java.lang.Long value) {
		this.editUserId = value;
	}

	public String toString() {
		return new ToStringBuilder(this,ToStringStyle.MULTI_LINE_STYLE)
			.append("Id",getId())
			.append("Title",getTitle())
			.append("Num",getNum())
			.append("Score",getScore())
			.append("IsStopLogin",getIsStopLogin())
			.append("AddTime",getAddTime())
			.append("ValidStartTime",getValidStartTime())
			.append("ValidStopTime",getValidStopTime())
			.append("BeginTime",getBeginTime())
			.append("EndTime",getEndTime())
			.append("RuleType",getRuleType())
			.append("ScoreType",getScoreType())
			.append("EditUserId",getEditUserId())
			.append("EditTime",getEditTime())
			.append("Status",getStatus())
			.append("Minute",getMinute())
			.append("IsDefault",getIsDefault())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof CommonRule == false) return false;
		if(this == obj) return true;
		CommonRule other = (CommonRule)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
	
	@Transient
	public AuthUser getEditUser(){
		AuthUserManager authUserManager = (AuthUserManager)ApplicationContextHolder.getBean("authUserManager");
		AuthUser user = null;
		if(null != this.getEditUserId()){
			user = authUserManager.getById(this.getEditUserId());
		}
		if(null == user){
			user = new AuthUser();
		}
		return user;
	}
	
	@Transient

jtzs-src/com/xes/jtzs/model/Grade.java
/*
 * Powered By [up72-framework]
 * Web Site: http://www.up72.com
 * Since 2006 - 2013
 */

package com.xes.jtzs.model;

import static com.up72.common.CommonUtils.*;
import java.util.Date;

import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;

import javax.validation.constraints.*;

import org.hibernate.validator.constraints.*;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;
import java.util.*;

import com.up72.base.*;
import com.up72.util.*;

import com.up72.framework.util.*;
import com.up72.framework.web.util.*;
import com.up72.framework.page.*;
import com.up72.framework.page.impl.*;

import com.xes.jtzs.JTZSConstants;
import com.xes.jtzs.model.*;
import com.xes.jtzs.dao.*;
import com.xes.jtzs.service.*;
import com.xes.jtzs.vo.query.*;/**
 * 
 * 
 * @author 
 * @version 1.0
 * @since 1.0
 */
@Entity
@Table(name = "xes_jtzs_grade")
public class Grade extends BaseEntity implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	//alias
	public static final String TABLE_ALIAS = "年级";
	public static final String ALIAS_ID = "id";
	public static final String ALIAS_NAME = "年级名称";
	public static final String ALIAS_SORT = "排序";
	public static final String ALIAS_DIVISION = "年部";
	
	//date formats
	

	//可以直接使用: @Length(max=50,message="用户名长度不能大于50")显示错误消息
	//columns START
	/** */
	
	private java.lang.Long id;
	
	/** 年级名称*/
	@Length(max=50)
	private java.lang.String name;
	
	/** 排序*/
	
	private java.lang.Long sort;
	/** 年部*/
	@Max(127)
	private Integer division;
	//columns END


	public Grade(){
	}

	public Grade(
		java.lang.Long id
	){
		this.id = id;
	}

	

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Column(name = "ID", unique = true, nullable = false, insertable = true, updatable = true, length = 19)
	public java.lang.Long getId() {
		return this.id;
	}
	
	@Column(name = "NAME", unique = false, nullable = true, insertable = true, updatable = true, length = 50)
	public java.lang.String getName() {
		return this.name;
	}
	
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	@Column(name = "SORT", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getSort() {
		return this.sort;
	}
	
	public void setSort(java.lang.Long value) {
		this.sort = value;
	}
	
	@Column(name = "DIVISION", unique = false, nullable = true, insertable = true, updatable = true, length = 3)
	public Integer getDivision() {
		return this.division;
	}
	
	public void setDivision(Integer value) {
		this.division = value;
	}
	
	public String toString() {
		return new ToStringBuilder(this,ToStringStyle.MULTI_LINE_STYLE)
			.append("Id",getId())
			.append("Name",getName())
			.append("Sort",getSort())
			.append("Division",getDivision())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof Grade == false) return false;
		if(this == obj) return true;
		Grade other = (Grade)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
	
	@Transient
	public String getDivisionName(){
		return JTZSConstants.Division.getName(this.getDivision());
	}
}

WebRoot/pages/admin/jtzs/score/base.jsp
<jsp:include page="/admin/adminBase" />

WebRoot/pages/admin/jtzs/score/batch_edit.jsp
<%@page import="com.xes.jtzs.model.*" %>
<%@ page trimDirectiveWhitespaces="true" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp" %>
<div class="up72_edit">
  <table border="0" cellspacing="0" cellpadding="0" width="100%" class="edit_table">
    <tr class="frmtr">
      <th class="frmth"><label><%=Score.ALIAS_ROLE%>：</label></th>
      <td class="frmtd">        <input id="role" class=" input_txt" maxlength="50" />
         </td>
    </tr>
    <tr class="frmtr">
      <th class="frmth"><label><%=Score.ALIAS_LOGIN_ID%>：</label></th>
      <td class="frmtd">        <input id="loginId" class="digits  input_txt" maxlength="19" />
         </td>
    </tr>
    <tr class="frmtr">
      <th class="frmth"><label><%=Score.ALIAS_SCORE%>：</label></th>
      <td class="frmtd">        <input id="score" class="digits  input_txt" maxlength="19" />
         </td>
    </tr>
    <tr class="frmtr">
      <th class="frmth"><label><%=Score.ALIAS_USE_SCORE%>：</label></th>
      <td class="frmtd">        <input id="useScore" class="digits  input_txt" maxlength="19" />
         </td>
    </tr>
  </table>
</div>

WebRoot/pages/admin/jtzs/score/selectScoreLog.jsp
<%@page import="com.xes.jtzs.model.*" %>

<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib tagdir="/WEB-INF/tags/simpletable" prefix="simpletable"%>
<%@ include file="/common/taglibs.jsp" %>
<%@ page trimDirectiveWhitespaces="true" %>
  <title><%=ScoreLog.TABLE_ALIAS%> 维护</title>
  <script src="${ctx}/scripts/rest.js" ></script>
  <link href="${ctx}/scripts/simpletable/simpletable.css" type="text/css" rel="stylesheet">
   <%@include file="/pages/admin/include/default/resource.jsp" %>
  <link href="${ctx}/styles/default/structs_inner.css" type="text/css" rel="stylesheet">
  <script type="text/javascript" src="${ctx}/scripts/simpletable/simpletable.js"></script> 
  <script type="text/javascript" src="${ctx}/scripts/columnshow.js"></script>
  <link href="${ctx}/scripts/grid/css/flexigrid.css" type="text/css" rel="stylesheet">
  <script type="text/javascript" src="${ctx}/scripts/grid/flexigrid-source.js"></script> 
  <script type="text/javascript" >
		$(document).ready(function() {
			// 分页需要依赖的初始化动作
			window.simpleTable = new SimpleTable('admin_jtzs_scoreLog_search_form',${page.thisPageNumber},${page.pageSize},'${pageRequest.sortColumns}');
		});
	</script> 
  <script type="text/javascript" src="<c:url value="/scripts/extend.div.1.0.js"/>"></script> 
  <!--搜索-->
  <div class="up72_search">
    <form id="admin_jtzs_scoreLog_search_form" name="admin_jtzs_scoreLog_search_form"  action="${ctx}/admin/jtzs/score/selectScoreLog">
      <div class="search_con"> 

        <input type="hidden" id="userRole" name="userRole" value="<c:out value="${query.userRole }"></c:out>"/> 
        <input type="hidden" id="userId" name="userId" value="<c:out value="${query.userId }"></c:out>"/> 
        <input type="hidden" id="remainScore" name="remainScore" value="<c:out value="${remainScore }"></c:out>"/> 
        <div class="search_txt"><%=ScoreLog.ALIAS_ADD_TIME%>：
         <input value="<fmt:formatDate value="${query.startTimeDate}" pattern="yyyy-MM-dd HH:mm"/>" onclick="WdatePicker({readOnly:true,dateFmt:'yyyy-MM-dd HH:mm'})" id="startTime" name="startTime" class=" input_text" />至
         <input value="<fmt:formatDate value="${query.endTimeDate}" pattern="yyyy-MM-dd HH:mm"/>" onclick="WdatePicker({readOnly:true,dateFmt:'yyyy-MM-dd HH:mm'})" id="endTime" name="endTime"   class=" input_text" />
         
         
        </div>

        <div class="search_txt"><%=ScoreLog.ALIAS_SCORE_TYPE%>：
          <select id="scoreType" name="scoreType"> 
            <option  value=""  <c:if test="${query.scoreType==null}">selected="selected"</c:if>>全部</option>
            <option  value="1" <c:if test="${query.scoreType==1}">selected="selected"</c:if>>获得</option>
            <option  value="2" <c:if test="${query.scoreType==2}">selected="selected"</c:if>>消耗</option>
          </select>
        </div>
        <div class="search_btn">
          <div class="input_button">
            <button name="btnU" type="submit"  class="button" value="查询"><span>查询</span></button>
          </div>
           <div class="input_button">
            <button name="exp" type="button" onclick="exports()" class="button" value="导出"><span>导出</span></button>
          </div>
        </div>
        
      </div>
    </form>
  </div>
  <!--end搜索-->
  
  <form id="admin_jtzs_scoreLog_page_form" name="admin_jtzs_scoreLog_page_form" method="get">
    <table id="admin_jtzs_scoreLog_table">
                         <tr>剩余积分:
                         <c:out value="${remainScore }"></c:out>
                         </tr>
     <thead>
           <tr>
                    <th sortColumn="SCORE_TYPE" showColumn="scoreType" width="100"><%=ScoreLog.ALIAS_SCORE_TYPE%></th>
                    <th sortColumn="CONTENT" showColumn="content" width="300"><%=ScoreLog.ALIAS_CONTENT%></th>
                    <th sortColumn="SCORE" showColumn="score" width="100"><%=ScoreLog.ALIAS_SCORE%></th>
                    <th sortColumn="ADD_TIME" showColumn="addTime" width="100"><%=ScoreLog.ALIAS_ADD_TIME%></th>
                    <th sortColumn="REMARK" showColumn="remark" width="200"><%=ScoreLog.ALIAS_REMARK%></th>
           </tr>
      </thead>
      <tbody>
        <c:forEach items="${page.result}" var="item" varStatus="status">
              <tr >
                  <td showColumn="scoreType">
                  <c:if test="${item.scoreType == 1}">获得</c:if>
                  <c:if test="${item.scoreType == 2}">消耗</c:if>
                  </td>
                  
                  <td showColumn="content"><c:out value='${item.content}'/></td>
                  
                  <td showColumn="score" align="center"><c:out value='${item.score}'/></td>
 
           
                  <td showColumn="addTime"><fmt:formatDate value="${item.addTimeDate}" pattern="yyyy-MM-dd HH:mm"/></td>
           
           
                  <td showColumn="remark"><c:out value='${item.remark}'/></td>
           
           
           
             </tr>
        </c:forEach>
      </tbody>
    </table>
    <simpletable:pageToolbar page="${page}"></simpletable:pageToolbar>
  </form>
   <form id="ff" method="post"></form>
  <script type="text/javascript">
	// 列选择显示处理
	$.showcolumn(${showColumn});
	// 排序处理
	$.sortcolumn({
		form : "#admin_jtzs_scoreLog_search_form",
		data : "pageNumber=${page.thisPageNumber}&pageSize=${page.pageSize}",
		columns : $("#admin_jtzs_scoreLog_table th[sortColumn]"),
		sortColumns : "${pageRequest.sortColumns}"
	});
	
	// 表格列表处理
	$('#admin_jtzs_scoreLog_table').flexigrid({
		height: 'auto',
		striped : true,
		buttons : [
		]
	});
	function exports(){
		var userId = $("#userId").val();
		var userRole = $("#userRole").val();
		var startTime = $("#startTime").val();
		var endTime  = $("#endTime").val();
		
		$("#ff").attr("action","${ctx}/admin/jtzs/scoreLog/exportData?userId="+userId+"&userRole="+userRole+"&startTime="+startTime+"&endTime="+endTime).submit();
		
	
		
	}
</script> 