module-src/com/up72/sys/model/BaseEntity.java
package com.up72.sys.model;

/**
 * Simple JavaBean domain object with an id property.
 * Used as a base class for objects needing this property.
 *
 * @author 贺杰
 */
public class BaseEntity {

	private Long id;
	

	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}

	public boolean isNew() {
		return (this.id == null);
	}

}

module-src/com/up72/sys/model/DataChangLog.java
/*
 * Powered By [up72-framework]
 * Web Site: http://www.up72.com
 * Since 2006 - 2012
 */

package com.up72.sys.model;

import static com.up72.common.CommonUtils.dateUtils;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;
import org.hibernate.validator.constraints.Length;

import com.up72.dao.hibernate.CommonDAOHibernate;
import com.up72.framework.util.holder.ApplicationContextHolder;

/**
 * 
 * 
 * @author up72
 * @version 1.0
 * @since 1.0
 */
@Entity
@Table(name = "sys_data_chang_log")
public class DataChangLog extends BaseEntity implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	//alias
	public static final String TABLE_ALIAS = "数据变更日志";
	public static final String ALIAS_ID = "ID";
	public static final String ALIAS_CHANG_TABLE = "变更表";
	public static final String ALIAS_CHANG_ID = "变更ID";
	public static final String ALIAS_CHANG_TIME = "变更时间";
	public static final String ALIAS_CHANG_TYPE = "变更类型"; // insert update delete
	
	public static final String CHANG_TYPE_CREATE = "insert";
	public static final String CHANG_TYPE_DELETE = "delete";
	public static final String CHANG_TYPE_UPDATE = "update";

	//可以直接使用: @Length(max=50,message="用户名长度不能大于50")显示错误消息
	//columns START
	/** */
	
	private java.lang.Long id;
	
	/** */
	@Length(max=256)
	private java.lang.String changTable;
	
	/** */
	
	private java.lang.Long changId;
	
	/** */
	private java.lang.Long changTime;
	
	/** */
	@Length(max=50)
	private java.lang.String changType;
	
	//columns END


	public DataChangLog(){
	}

	public DataChangLog(
		java.lang.Long id
	){
		this.id = id;
	}

	

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Column(name = "ID", unique = true, nullable = false, insertable = true, updatable = true, length = 19)
	public java.lang.Long getId() {
		return this.id;
	}
	
	@Column(name = "CHANG_TABLE", unique = false, nullable = true, insertable = true, updatable = true, length = 256)
	public java.lang.String getChangTable() {
		return this.changTable;
	}
	
	public void setChangTable(java.lang.String value) {
		this.changTable = value;
	}
	
	@Column(name = "CHANG_ID", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getChangId() {
		return this.changId;
	}
	
	public void setChangId(java.lang.Long value) {
		this.changId = value;
	}
	
	@Transient
	public Date getChangTimeDate() {
		return dateUtils.longToDate(this.changTime);
	}
	
	@Column(name = "CHANG_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
	public java.lang.Long getChangTime() {
		return this.changTime;
	}
	
	public void setChangTime(java.lang.Long value) {
		this.changTime = value;
	}
	
	@Column(name = "CHANG_TYPE", unique = false, nullable = true, insertable = true, updatable = true, length = 50)
	public java.lang.String getChangType() {
		return this.changType;
	}
	
	public void setChangType(java.lang.String value) {
		this.changType = value;
	}
	

	public String toString() {
		return new ToStringBuilder(this,ToStringStyle.MULTI_LINE_STYLE)
			.append("Id",getId())
			.append("ChangTable",getChangTable())
			.append("ChangId",getChangId())
			.append("ChangTime",getChangTime())
			.append("ChangType",getChangType())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof DataChangLog == false) return false;
		if(this == obj) return true;
		DataChangLog other = (DataChangLog)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
	
	@Transient
	public Object getChangObject(){
		Object result = null;
		if(null == changId || null == changTable || changTable.trim().equals("")){
			return result;
		}
		else {
			try{
				CommonDAOHibernate commonDAOHibernate = (CommonDAOHibernate) ApplicationContextHolder.getBean("commonDAOHibernate");
				String hsql = "from "+this.changTable+" where id=?";
				List list = commonDAOHibernate.find(hsql, new Object[]{this.changId});
				if(null != list && !list.isEmpty()){
					result = list.get(0);
				}
			}catch (Exception e) {
				result = null;
			}
		}
		return result;
	}
}

module-src/com/up72/sys/model/IModelSearch.java
package com.up72.sys.model;

public interface IModelSearch
{
	public String getLinkUrl();
	public String getSearchTitle();
	public String getSearchContent();
}

module-src/com/up72/base/BaseRestSpringController.java
package com.up72.base;

import static com.up72.common.CommonUtils.cookieUtil;
import static com.up72.common.CommonUtils.jsonUtil;
import static com.up72.common.CommonUtils.tokenUtil;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.ui.ModelMap;
import org.springframework.util.Assert;
import org.springframework.util.ReflectionUtils;

import com.up72.framework.beanutils.BeanUtils;
import com.up72.framework.page.Page;
import com.up72.framework.page.PageRequest;
import com.up72.page.PageRequestFactory;
import com.up72.util.ConvertRegisterHelper;

/**
 * 标准的rest方法列表
 * 
 * <pre>
 * /userinfo                =&gt; index()  
 * /userinfo/new            =&gt; _new()  注意: 不使用/userinfo/add =&gt; add()的原因是ad会被一些浏览器当做广告URL拦截
 * /userinfo/{id}           =&gt; show()  
 * /userinfo/{id}/edit      =&gt; edit()  
 * /userinfo        POST    =&gt; create()  
 * /userinfo/{id}   PUT     =&gt; update()  
 * /userinfo/{id}   DELETE  =&gt; delete()  
 * /userinfo        DELETE  =&gt; batchDelete()  
 * </pre>
 * 
 * @author up72
 */
public class BaseRestSpringController<Entity, PK> {
	protected final static String SUCCESS = "success";
	protected final static String ERROR = "error";
	
	protected final static Boolean RLT_SUCCESS = true;
	protected final static Boolean RLT_ERROR = false;
	
	protected final static String STATUS = "status";
	protected final static String MESSAGE = "message";
	
	protected final static String SAVE_SUCCESS = "保存成功";
	protected final static String CREATED_SUCCESS = "创建成功";
	protected final static String UPDATE_SUCCESS = "更新成功";
	protected final static String DELETE_SUCCESS = "删除成功";
	protected final static String OPRATE_SUCCESS = "操作成功";
	protected final static String SEND_SUCCESS =   "发送成功";
	protected final static String FREEZE_SUCCESS =  "冻结成功";
	protected final static String EXPORT_SUCCESS =  "导出成功";
	
	protected Log log = LogFactory.getLog(getClass());

	/** 定义分页传参 PAGINATION_START 页面起始数据 PAGINATION_RANGE分页大小 */
	public final static String PAGINATION_START = "start";
	public final static String PAGINATION_RANGE = "range";
	/** 定义系统数据字典类别默认分页大小 */

	public final static int DEFAULT_RANGE = 20;

	static {
		// 注册converters
		ConvertRegisterHelper.registerConverters();
	}

	public static void copyProperties(Object target, Object source) {
		BeanUtils.copyProperties(target, source);
	}

	public static <T> T copyProperties(Class<T> destClass, Object orig) {
		return BeanUtils.copyProperties(destClass, orig);
	}

	@SuppressWarnings( { "unchecked" })
	public ModelMap toModelMap(Page page, PageRequest pageRequest) {
		return toModelMap("", page, pageRequest);
	}

	@SuppressWarnings( { "unchecked" })
	public ModelMap toModelMap(String tableId, Page page,
			PageRequest pageRequest) {
		ModelMap model = new ModelMap();
		saveIntoModelMap(tableId, page, pageRequest, model);
		return model;
	}

	/**
	 * 用于一个页面有多个extremeTable是使用
	 * 
	 * @param tableId
	 *            等于extremeTable的tableId属性
	 */
	@SuppressWarnings( { "unchecked" })
	public static void saveIntoModelMap(String tableId, Page page,
			PageRequest pageRequest, ModelMap model) {
		Assert.notNull(tableId, "tableId must be not null");
		Assert.notNull(page, "page must be not null");
		
		model.addAttribute(tableId + "page", page);
		model.addAttribute(tableId + "totalRows", new Integer(page
				.getTotalCount()));
		model.addAttribute(tableId + "pageRequest", pageRequest);
		model.addAttribute(tableId + "query", pageRequest);
	}

	@SuppressWarnings( { "unchecked" })
	public static PageRequest bindPageRequest(HttpServletRequest request,
			PageRequest pageRequest, String defaultSortColumns) {
		return PageRequestFactory.bindPageRequest(pageRequest, request,
				defaultSortColumns);
	}

	@SuppressWarnings( { "unchecked" })
	public static <T> T getOrCreateRequestAttribute(HttpServletRequest request,
			String key, Class<T> clazz) {
		Object value = request.getAttribute(key);
		if (value == null) {
			try {
				value = clazz.newInstance();
			} catch (Exception e) {
				ReflectionUtils.handleReflectionException(e);
			}
			request.setAttribute(key, value);
		}
		return (T) value;
	}

	/** 显示列属性值 */
	private static final String SHOW_LABLE_VALUE ="showColumn";
	/** 显示列标签字段 */
	private static final String SHOW_COLUMN ="showColumn";
	/** 显示列标签存储cookie时长 */
	private static final Integer SHOW_COLUMN_COOKIE_TIME = 3600*24*30;
	/**
	 * 列排序处理方法
	 * 
	 * @param url
	 *            需要排序处理的页面url
	 * @return 需要排序
	 * @author wqtan
	 */
	private String getJsonShowLable(String url, HttpServletRequest request,
			HttpServletResponse response) throws IOException {
		if (null != url && !url.trim().equals("")) {
			if (url.indexOf('?') != -1) {
				url = url.substring(0, url.indexOf('?'));
			}
			url = url.replace('/', '_');
		}
		String[] showlables = request
				.getParameterValues(SHOW_LABLE_VALUE);
		String result = "";
		
		if (null != showlables && showlables.length > 0) {
			result = jsonUtil.object2Json(showlables);
			cookieUtil.setCookie(response, 
					url + SHOW_LABLE_VALUE, result,
					SHOW_COLUMN_COOKIE_TIME);
		} else {
			result = cookieUtil.getString(request, 
					url + SHOW_LABLE_VALUE);
		}
		return result;
	}
	
	/**
	 * 前台列表显示列处理
	 */
	protected void addShowLabelAttrbite(String key,ModelMap model,HttpServletRequest request,HttpServletResponse response) throws IOException{
		model.addAttribute(SHOW_COLUMN,this.getJsonShowLable(key,request, response));
	}
	/**
	 * 前台列表显示列处理
	 */
	protected void addShowLabelAttrbite(String key,HttpServletRequest request,HttpServletResponse response) throws IOException{
		request.setAttribute(SHOW_COLUMN,this.getJsonShowLable(key,request, response));
	}
	
	
	/**
	 * 生成Token值
	 * @author bxmen
	 * @param request 
	 * @summary 
	 */
	public static void createToken(HttpServletRequest request){
		tokenUtil.createToken(request);
	}
	
	/**
	 * 验证Token是否有效，有效可以处理数据，无效跳转到错误提示页面
	 * @author bxmen
	 * @param request
	 * @return boolean
	 * @summary 
	 */
	public static boolean validateToken(HttpServletRequest request){
		boolean result = false;
		if(tokenUtil.isTokenValid(request)){
			tokenUtil.destroyToken(request);
			result = true;
		}
		return result;
	}
}

module-src/com/up72/sys/controller/AdminDataChangLogController.java
/*
 * Powered By [up72-framework]
 * Web Site: http://www.up72.com
 * Since 2006 - 2012
 */


package com.up72.sys.controller;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import org.springframework.beans.propertyeditors.CustomDateEditor;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.up72.base.BaseRestSpringController;
import com.up72.framework.page.Page;
import com.up72.framework.web.scope.Flash;
import com.up72.sys.model.DataChangLog;
import com.up72.sys.service.DataChangLogManager;
import com.up72.sys.vo.query.DataChangLogQuery;
/**
 * 数据提取跳转
 * 
 * @author up72
 * @version 1.0
 * @since 1.0
 */
@Controller
@RequestMapping("/admin/sys/dataChangLog")
public class AdminDataChangLogController extends BaseRestSpringController<DataChangLog,java.lang.Long>{
	//默认多列排序,example: username desc,createTime asc
	protected static final String DEFAULT_SORT_COLUMNS = null; 
	
	private DataChangLogManager dataChangLogManager;
	
	private final String LIST_ACTION = "redirect:/admin/sys/dataChangLog";
	
	/** 
	 * 增加setXXXX()方法,spring就可以通过autowire自动设置对象属性,注意大小写
	 **/
	public void setDataChangLogManager(DataChangLogManager manager) {
		this.dataChangLogManager = manager;
	}
	
	/** binder用于bean属性的设置 */
	@InitBinder  
	public void initBinder(WebDataBinder binder) {  
	        binder.registerCustomEditor(Date.class, new CustomDateEditor(new SimpleDateFormat("yyyy-MM-dd"), true));  
	}
	   
	/**
	 * 增加了@ModelAttribute的方法可以在本controller方法调用前执行,可以存放一些共享变量,如枚举值,或是一些初始化操作
	 */
	@ModelAttribute
	public void init(ModelMap model) {
		//model.put("now", new java.sql.Timestamp(System.currentTimeMillis()));
	}
	
	/** 列表  
	  * @throws IOException */
	@RequestMapping
	@SuppressWarnings({ "unchecked" })
	public String index(ModelMap model,DataChangLogQuery query,HttpServletRequest request,HttpServletResponse response) throws IOException {
		Page page = this.dataChangLogManager.findPage(query);
		
		model.addAllAttributes(toModelMap(page, query));
		
		this.addShowLabelAttrbite("/admin/sys/dataChangLog",model,request,response);
		return "/admin/sys/dataChangLog/index";
	}
	
	/** 显示 */
	@RequestMapping(value="/{id}")
	public String show(ModelMap model,@PathVariable java.lang.Long id) throws Exception {
		DataChangLog dataChangLog = (DataChangLog)dataChangLogManager.getById(id);
		model.addAttribute("dataChangLog",dataChangLog);
		return "/admin/sys/dataChangLog/show";
	}

	/** 进入新增 */
	@RequestMapping(value="/new")
	public String _new(ModelMap model,DataChangLog dataChangLog,HttpServletRequest request,HttpServletResponse response) throws Exception {
		model.addAttribute("dataChangLog",dataChangLog);
		return "/admin/sys/dataChangLog/new";
	}
	
	/** 保存新增,@Valid标注spirng在绑定对象时自动为我们验证对象属性并存放errors在BindingResult  */
	@RequestMapping(method=RequestMethod.POST)
	public String create(ModelMap model,@Valid DataChangLog dataChangLog,BindingResult errors,HttpServletRequest request,HttpServletResponse response) throws Exception {
		if(errors.hasErrors()) {
			return  "/admin/sys/dataChangLog/new";
		}
		
		dataChangLogManager.save(dataChangLog);
		Flash.current().success(CREATED_SUCCESS); //存放在Flash中的数据,在下一次http请求中仍然可以读取数据,error()用于显示错误消息
		return LIST_ACTION;
	}
	
	/** 编辑 */
	@RequestMapping(value="/{id}/edit")
	public String edit(ModelMap model,@PathVariable java.lang.Long id) throws Exception {
		DataChangLog dataChangLog = (DataChangLog)dataChangLogManager.getById(id);
		model.addAttribute("dataChangLog",dataChangLog);
		return "/admin/sys/dataChangLog/edit";
	}
	
	/** 选项卡编辑 */
	@RequestMapping(value="/{id}/tabEdit")
	public String tabEdit(ModelMap model,@PathVariable java.lang.Long id) throws Exception {
		DataChangLog dataChangLog = (DataChangLog)dataChangLogManager.getById(id);
		model.addAttribute("dataChangLog",dataChangLog);
		return "/admin/sys/dataChangLog/tab_edit";
	}
	
	
	/** 选项卡显示 */
	@RequestMapping(value="/{id}/tabShow")
	public String tabShow(ModelMap model,@PathVariable java.lang.Long id) throws Exception {
		DataChangLog dataChangLog = (DataChangLog)dataChangLogManager.getById(id);
		model.addAttribute("dataChangLog",dataChangLog);
		return "/admin/sys/dataChangLog/tab_show";
	}
	
	/** 保存更新,@Valid标注spirng在绑定对象时自动为我们验证对象属性并存放errors在BindingResult  */
	@RequestMapping(value="/{id}",method=RequestMethod.PUT)
	public String update(ModelMap model,@PathVariable java.lang.Long id,@Valid DataChangLog dataChangLog,BindingResult errors,HttpServletRequest request,HttpServletResponse response) throws Exception {
		if(errors.hasErrors()) {
			return "/admin/sys/dataChangLog/edit";
		}
		
		dataChangLogManager.update(dataChangLog);
		Flash.current().success(UPDATE_SUCCESS);
		return LIST_ACTION;
	}
	
	/** 删除 */
	@RequestMapping(value="/{id}",method=RequestMethod.DELETE)
	public String delete(ModelMap model,@PathVariable java.lang.Long id) {
		dataChangLogManager.removeById(id);
		Flash.current().success(DELETE_SUCCESS);
		return LIST_ACTION;
	}

	/** 批量删除 */
	@RequestMapping(method=RequestMethod.DELETE)
	public String batchDelete(ModelMap model,@RequestParam("items") java.lang.Long[] items) {
		for(int i = 0; i < items.length; i++) {
			dataChangLogManager.removeById(items[i]);
		}
		Flash.current().success(DELETE_SUCCESS);
		return LIST_ACTION;
	}
	
}

WebRoot/pages/admin/sys/dataChangLog/base.jsp
<jsp:include page="/admin/adminBase" />

WebRoot/pages/admin/sys/dataChangLog/batch_edit.jsp
<%@page import="com.up72.sys.model.*" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp" %>

<div class="up72_edit">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" class="edit_table">
	
		<tr class="pb_frmtr">
			<th class="pb_frmth"><label><%=DataChangLog.ALIAS_CHANG_TABLE%>：</label></th>
			<td class="pb_frmtd"><input id="changTable" class="input_txt" maxlength="256" /></td>
		</tr>
		<tr class="pb_frmtr">
			<th class="pb_frmth"><label><%=DataChangLog.ALIAS_CHANG_ID%>：</label></th>
			<td class="pb_frmtd"><input id="changId" class="digits input_txt" maxlength="19" /></td>
		</tr>
		<tr class="pb_frmtr">
			<th class="pb_frmth"><label><%=DataChangLog.ALIAS_CHANG_TIME%>：</label></th>
			<td class="pb_frmtd"><input onclick="WdatePicker({dateFmt:'<%=DataChangLog.FORMAT_CHANG_TIME%>'})" id="changTimeString" name="changTimeString"  maxlength="0" class="input_txt" /></td>
		</tr>
		<tr class="pb_frmtr">
			<th class="pb_frmth"><label><%=DataChangLog.ALIAS_CHANG_TYPE%>：</label></th>
			<td class="pb_frmtd"><input id="changType" class="input_txt" maxlength="50" /></td>
		</tr>
	</table>
</div>

WebRoot/pages/admin/sys/dataChangLog/edit.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp" %>

<div class="up72_edit">
  <form:form id="admin_sys_dataChangLog_edit_form" method="put" action="${ctx}/admin/sys/dataChangLog/${dataChangLog.id}" modelAttribute="dataChangLog">
    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="edit_table">
      <%@ include file="form_include.jsp" %>
    </table>
    <div class="up72_submit">
      <div class="btn btn_sub" title="完成"><input type="submit" id="submitButton" name="submitButton" value="完成" /></div>
      <div class="btn btn_cel" title="取消"><input type="button" id="close_button" value="取消" onclick="closeBox();" /></div>
    </div>
  </form:form>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$("#admin_sys_dataChangLog_edit_form").validate({
				/*  
				// ajax提交方式
				submitHandler:function(form){   
					form.submit();
				},
				*/
				errorPlacement: function(error, element) {
					error.appendTo(element.parent());
				}
		});	
	});
</script>

WebRoot/pages/admin/sys/dataChangLog/form_include.jsp
<%@page import="com.up72.sys.model.*" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp" %>

	<input type="hidden" id="id" name="id" value="${dataChangLog.id}"/>

	 <tr class="pb_frmtr">
		<th class="pb_frmth"><label><%=DataChangLog.ALIAS_CHANG_TABLE%>:</label></th>	
		 <td class="pb_frmtd">
		<form:input path="changTable" id="changTable" class="input_txt" maxlength="256" />
		<font color='red'><form:errors path="changTable"/></font>
		</td>
	</tr>	
	 <tr class="pb_frmtr">
		<th class="pb_frmth"><label><%=DataChangLog.ALIAS_CHANG_ID%>:</label></th>	
		 <td class="pb_frmtd">
		<form:input path="changId" id="changId" class="digits  input_txt" maxlength="19" />
		<font color='red'><form:errors path="changId"/></font>
		</td>
	</tr>	
	 <tr class="pb_frmtr">
		<th class="pb_frmth"><label><%=DataChangLog.ALIAS_CHANG_TIME%>:</label></th>	
		 <td class="pb_frmtd"><input value="<fmt:formatDate value="${dataChangLog.changTimeDate}" pattern="yyyy-MM-dd HH:ss"/>" onclick="WdatePicker({readOnly:true,dateFmt:'yyyy-MM-dd HH:ss'})" id="changTimeString" name="changTimeString"  maxlength="0" class="input_txt" />
		<font color='red'><form:errors path="changTime"/></font>
		</td>
	</tr>	
	 <tr class="pb_frmtr">
		<th class="pb_frmth"><label><%=DataChangLog.ALIAS_CHANG_TYPE%>:</label></th>	
		 <td class="pb_frmtd">
		<form:input path="changType" id="changType" class="input_txt" maxlength="50" />
		<font color='red'><form:errors path="changType"/></font>
		</td>
	</tr>	

WebRoot/pages/admin/sys/dataChangLog/new.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp" %>

<div class="up72_edit">
  <form:form id="admin_sys_dataChangLog_edit_form" method="post" action="${ctx}/admin/sys/dataChangLog/" modelAttribute="dataChangLog" >
    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="edit_table">
      <%@ include file="form_include.jsp" %>
    </table>
    <div class="up72_submit">
      <div class="btn btn_sub" title="完成"><input type="submit" id="submitButton" name="submitButton" value="完成" /></div>
      <div class="btn btn_cel" title="取消"><input type="button" id="close_button" value="取消" onclick="closeBox();" /></div>
    </div>
  </form:form>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$("#admin_sys_dataChangLog_edit_form").validate({
				/*  
				// ajax提交方式
				submitHandler:function(form){   
					form.submit();
				},
				*/
				errorPlacement: function(error, element) {
					error.appendTo(element.parent());
				}
		});	
	});
</script> 

WebRoot/pages/admin/sys/dataChangLog/tab_show.jsp
<%@page import="com.up72.sys.model.*" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

 
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp" %>

<div class="up72_edit">
   <table width="100%" border="0" cellspacing="0" cellpadding="0" class="edit_table">
   		<tr>
         	<th><%=DataChangLog.ALIAS_CHANG_TABLE%>：</th>
            <td><c:out value='${dataChangLog.changTable}'/></td>
     	 </tr>
   		<tr>
         	<th><%=DataChangLog.ALIAS_CHANG_ID%>：</th>
            <td><c:out value='${dataChangLog.changId}'/></td>
     	 </tr>
   		<tr>
         	<th><%=DataChangLog.ALIAS_CHANG_TIME%>：</th>
            <td><fmt:formatDate value="${dataChangLog.changTimeDate}"/></td>
     	 </tr>
   		<tr>
         	<th><%=DataChangLog.ALIAS_CHANG_TYPE%>：</th>
            <td><c:out value='${dataChangLog.changType}'/></td>
     	 </tr>
    </table>
	
 </div>